#!/bin/bash
clear
echo updating apt...
sudo apt-get update
echo installing curl...
sudo apt-get install curl -y
echo installing rvm...
\curl -L https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
echo installing rvm requirements...
rvm requirements
echo installing ruby...
rvm install 2.0.0
echo setting default ruby...
rvm use 2.0.0 --default
echo installing rubygems...
rvm rubygems current
echo installing rails...
gem install --no-rdoc --no-ri rails
echo installing some other stuff...
sudo apt-get install git postgresql postgresql-server-dev-9.1 -y
